/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalMyDslParser;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

public class MyDslParser extends AbstractContentAssistParser {

	@Inject
	private MyDslGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalMyDslParser createParser() {
		InternalMyDslParser result = new InternalMyDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getElementAccess().getAlternatives(), "rule__Element__Alternatives");
					put(grammarAccess.getEFloatAccess().getAlternatives_4_0(), "rule__EFloat__Alternatives_4_0");
					put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
					put(grammarAccess.getEBooleanAccess().getAlternatives(), "rule__EBoolean__Alternatives");
					put(grammarAccess.getDBSystemAccess().getAlternatives(), "rule__DBSystem__Alternatives");
					put(grammarAccess.getColorsAccess().getAlternatives(), "rule__Colors__Alternatives");
					put(grammarAccess.getPositionOptionsAccess().getAlternatives(), "rule__PositionOptions__Alternatives");
					put(grammarAccess.getCompanyAccess().getGroup(), "rule__Company__Group__0");
					put(grammarAccess.getCompanyAccess().getGroup_2(), "rule__Company__Group_2__0");
					put(grammarAccess.getCompanyAccess().getGroup_8(), "rule__Company__Group_8__0");
					put(grammarAccess.getCompanyAccess().getGroup_14(), "rule__Company__Group_14__0");
					put(grammarAccess.getDashboardAccess().getGroup(), "rule__Dashboard__Group__0");
					put(grammarAccess.getDashboardAccess().getGroup_6(), "rule__Dashboard__Group_6__0");
					put(grammarAccess.getPanelAccess().getGroup(), "rule__Panel__Group__0");
					put(grammarAccess.getPanelAccess().getGroup_6(), "rule__Panel__Group_6__0");
					put(grammarAccess.getTableAccess().getGroup(), "rule__Table__Group__0");
					put(grammarAccess.getTableAccess().getGroup_2(), "rule__Table__Group_2__0");
					put(grammarAccess.getTableAccess().getGroup_3(), "rule__Table__Group_3__0");
					put(grammarAccess.getTableAccess().getGroup_4(), "rule__Table__Group_4__0");
					put(grammarAccess.getTableAccess().getGroup_11(), "rule__Table__Group_11__0");
					put(grammarAccess.getMenuAccess().getGroup(), "rule__Menu__Group__0");
					put(grammarAccess.getMenuAccess().getGroup_3(), "rule__Menu__Group_3__0");
					put(grammarAccess.getMenuAccess().getGroup_8(), "rule__Menu__Group_8__0");
					put(grammarAccess.getOptionAccess().getGroup(), "rule__Option__Group__0");
					put(grammarAccess.getOptionAccess().getGroup_3(), "rule__Option__Group_3__0");
					put(grammarAccess.getOptionAccess().getGroup_4(), "rule__Option__Group_4__0");
					put(grammarAccess.getOptionAccess().getGroup_5(), "rule__Option__Group_5__0");
					put(grammarAccess.getLineChartAccess().getGroup(), "rule__LineChart__Group__0");
					put(grammarAccess.getLineChartAccess().getGroup_2(), "rule__LineChart__Group_2__0");
					put(grammarAccess.getLineChartAccess().getGroup_3(), "rule__LineChart__Group_3__0");
					put(grammarAccess.getLineChartAccess().getGroup_4(), "rule__LineChart__Group_4__0");
					put(grammarAccess.getLineChartAccess().getGroup_5(), "rule__LineChart__Group_5__0");
					put(grammarAccess.getLineChartAccess().getGroup_6(), "rule__LineChart__Group_6__0");
					put(grammarAccess.getLineChartAccess().getGroup_7(), "rule__LineChart__Group_7__0");
					put(grammarAccess.getLineChartAccess().getGroup_14(), "rule__LineChart__Group_14__0");
					put(grammarAccess.getLineChartAccess().getGroup_20(), "rule__LineChart__Group_20__0");
					put(grammarAccess.getBarChartAccess().getGroup(), "rule__BarChart__Group__0");
					put(grammarAccess.getBarChartAccess().getGroup_2(), "rule__BarChart__Group_2__0");
					put(grammarAccess.getBarChartAccess().getGroup_3(), "rule__BarChart__Group_3__0");
					put(grammarAccess.getBarChartAccess().getGroup_4(), "rule__BarChart__Group_4__0");
					put(grammarAccess.getBarChartAccess().getGroup_5(), "rule__BarChart__Group_5__0");
					put(grammarAccess.getBarChartAccess().getGroup_6(), "rule__BarChart__Group_6__0");
					put(grammarAccess.getBarChartAccess().getGroup_7(), "rule__BarChart__Group_7__0");
					put(grammarAccess.getBarChartAccess().getGroup_8(), "rule__BarChart__Group_8__0");
					put(grammarAccess.getBarChartAccess().getGroup_15(), "rule__BarChart__Group_15__0");
					put(grammarAccess.getBarChartAccess().getGroup_21(), "rule__BarChart__Group_21__0");
					put(grammarAccess.getRadarChartAccess().getGroup(), "rule__RadarChart__Group__0");
					put(grammarAccess.getRadarChartAccess().getGroup_2(), "rule__RadarChart__Group_2__0");
					put(grammarAccess.getRadarChartAccess().getGroup_3(), "rule__RadarChart__Group_3__0");
					put(grammarAccess.getRadarChartAccess().getGroup_9(), "rule__RadarChart__Group_9__0");
					put(grammarAccess.getRadarChartAccess().getGroup_15(), "rule__RadarChart__Group_15__0");
					put(grammarAccess.getPieChartAccess().getGroup(), "rule__PieChart__Group__0");
					put(grammarAccess.getPieChartAccess().getGroup_3(), "rule__PieChart__Group_3__0");
					put(grammarAccess.getPieChartAccess().getGroup_4(), "rule__PieChart__Group_4__0");
					put(grammarAccess.getPieChartAccess().getGroup_9(), "rule__PieChart__Group_9__0");
					put(grammarAccess.getPieChartAccess().getGroup_15(), "rule__PieChart__Group_15__0");
					put(grammarAccess.getActionAccess().getGroup(), "rule__Action__Group__0");
					put(grammarAccess.getActionAccess().getGroup_3(), "rule__Action__Group_3__0");
					put(grammarAccess.getActionAccess().getGroup_4(), "rule__Action__Group_4__0");
					put(grammarAccess.getColumnAccess().getGroup(), "rule__Column__Group__0");
					put(grammarAccess.getColumnAccess().getGroup_3(), "rule__Column__Group_3__0");
					put(grammarAccess.getColumnAccess().getGroup_4(), "rule__Column__Group_4__0");
					put(grammarAccess.getDataAccess().getGroup(), "rule__Data__Group__0");
					put(grammarAccess.getDataAccess().getGroup_2(), "rule__Data__Group_2__0");
					put(grammarAccess.getDataAccess().getGroup_3(), "rule__Data__Group_3__0");
					put(grammarAccess.getDataAccess().getGroup_4(), "rule__Data__Group_4__0");
					put(grammarAccess.getDataAccess().getGroup_5(), "rule__Data__Group_5__0");
					put(grammarAccess.getDataAccess().getGroup_10(), "rule__Data__Group_10__0");
					put(grammarAccess.getLabelAccess().getGroup(), "rule__Label__Group__0");
					put(grammarAccess.getDBServerAccess().getGroup(), "rule__DBServer__Group__0");
					put(grammarAccess.getDBServerAccess().getGroup_2(), "rule__DBServer__Group_2__0");
					put(grammarAccess.getDBServerAccess().getGroup_3(), "rule__DBServer__Group_3__0");
					put(grammarAccess.getDBServerAccess().getGroup_4(), "rule__DBServer__Group_4__0");
					put(grammarAccess.getDBServerAccess().getGroup_9(), "rule__DBServer__Group_9__0");
					put(grammarAccess.getCollectionAccess().getGroup(), "rule__Collection__Group__0");
					put(grammarAccess.getCollectionAccess().getGroup_6(), "rule__Collection__Group_6__0");
					put(grammarAccess.getDocumentAccess().getGroup(), "rule__Document__Group__0");
					put(grammarAccess.getEFloatAccess().getGroup(), "rule__EFloat__Group__0");
					put(grammarAccess.getEFloatAccess().getGroup_4(), "rule__EFloat__Group_4__0");
					put(grammarAccess.getEIntAccess().getGroup(), "rule__EInt__Group__0");
					put(grammarAccess.getCompanyAccess().getNameAssignment_1(), "rule__Company__NameAssignment_1");
					put(grammarAccess.getCompanyAccess().getNitAssignment_2_1(), "rule__Company__NitAssignment_2_1");
					put(grammarAccess.getCompanyAccess().getDashboardsAssignment_7(), "rule__Company__DashboardsAssignment_7");
					put(grammarAccess.getCompanyAccess().getDashboardsAssignment_8_1(), "rule__Company__DashboardsAssignment_8_1");
					put(grammarAccess.getCompanyAccess().getDBServersAssignment_13(), "rule__Company__DBServersAssignment_13");
					put(grammarAccess.getCompanyAccess().getDBServersAssignment_14_1(), "rule__Company__DBServersAssignment_14_1");
					put(grammarAccess.getDashboardAccess().getNameAssignment_1(), "rule__Dashboard__NameAssignment_1");
					put(grammarAccess.getDashboardAccess().getPanelsAssignment_5(), "rule__Dashboard__PanelsAssignment_5");
					put(grammarAccess.getDashboardAccess().getPanelsAssignment_6_1(), "rule__Dashboard__PanelsAssignment_6_1");
					put(grammarAccess.getPanelAccess().getNameAssignment_1(), "rule__Panel__NameAssignment_1");
					put(grammarAccess.getPanelAccess().getElementsAssignment_5(), "rule__Panel__ElementsAssignment_5");
					put(grammarAccess.getPanelAccess().getElementsAssignment_6_1(), "rule__Panel__ElementsAssignment_6_1");
					put(grammarAccess.getTableAccess().getNameAssignment_1(), "rule__Table__NameAssignment_1");
					put(grammarAccess.getTableAccess().getTitleAssignment_2_1(), "rule__Table__TitleAssignment_2_1");
					put(grammarAccess.getTableAccess().getRegistersPerPageAssignment_3_1(), "rule__Table__RegistersPerPageAssignment_3_1");
					put(grammarAccess.getTableAccess().getActionsAssignment_4_1(), "rule__Table__ActionsAssignment_4_1");
					put(grammarAccess.getTableAccess().getSearchAssignment_5(), "rule__Table__SearchAssignment_5");
					put(grammarAccess.getTableAccess().getAddAssignment_6(), "rule__Table__AddAssignment_6");
					put(grammarAccess.getTableAccess().getColumnsAssignment_10(), "rule__Table__ColumnsAssignment_10");
					put(grammarAccess.getTableAccess().getColumnsAssignment_11_1(), "rule__Table__ColumnsAssignment_11_1");
					put(grammarAccess.getMenuAccess().getNameAssignment_1(), "rule__Menu__NameAssignment_1");
					put(grammarAccess.getMenuAccess().getTitleAssignment_3_1(), "rule__Menu__TitleAssignment_3_1");
					put(grammarAccess.getMenuAccess().getOptionsAssignment_7(), "rule__Menu__OptionsAssignment_7");
					put(grammarAccess.getMenuAccess().getOptionsAssignment_8_1(), "rule__Menu__OptionsAssignment_8_1");
					put(grammarAccess.getOptionAccess().getNameAssignment_2(), "rule__Option__NameAssignment_2");
					put(grammarAccess.getOptionAccess().getIconAssignment_3_1(), "rule__Option__IconAssignment_3_1");
					put(grammarAccess.getOptionAccess().getTitleAssignment_4_1(), "rule__Option__TitleAssignment_4_1");
					put(grammarAccess.getOptionAccess().getUrlComponentAssignment_5_1(), "rule__Option__UrlComponentAssignment_5_1");
					put(grammarAccess.getLineChartAccess().getNameAssignment_1(), "rule__LineChart__NameAssignment_1");
					put(grammarAccess.getLineChartAccess().getTitleAssignment_2_1(), "rule__LineChart__TitleAssignment_2_1");
					put(grammarAccess.getLineChartAccess().getLegendPositionAssignment_3_1(), "rule__LineChart__LegendPositionAssignment_3_1");
					put(grammarAccess.getLineChartAccess().getLabelStringXAxesAssignment_4_1(), "rule__LineChart__LabelStringXAxesAssignment_4_1");
					put(grammarAccess.getLineChartAccess().getColorGridLinesXAxesAssignment_5_1(), "rule__LineChart__ColorGridLinesXAxesAssignment_5_1");
					put(grammarAccess.getLineChartAccess().getLabelStringYAxesAssignment_6_1(), "rule__LineChart__LabelStringYAxesAssignment_6_1");
					put(grammarAccess.getLineChartAccess().getColorGridLinesYAxesAssignment_7_1(), "rule__LineChart__ColorGridLinesYAxesAssignment_7_1");
					put(grammarAccess.getLineChartAccess().getDisplayGridLinesXAxesAssignment_8(), "rule__LineChart__DisplayGridLinesXAxesAssignment_8");
					put(grammarAccess.getLineChartAccess().getDisplayGridLinesYAxesAssignment_9(), "rule__LineChart__DisplayGridLinesYAxesAssignment_9");
					put(grammarAccess.getLineChartAccess().getDataAssignment_13(), "rule__LineChart__DataAssignment_13");
					put(grammarAccess.getLineChartAccess().getDataAssignment_14_1(), "rule__LineChart__DataAssignment_14_1");
					put(grammarAccess.getLineChartAccess().getLabelsAssignment_19(), "rule__LineChart__LabelsAssignment_19");
					put(grammarAccess.getLineChartAccess().getLabelsAssignment_20_1(), "rule__LineChart__LabelsAssignment_20_1");
					put(grammarAccess.getBarChartAccess().getNameAssignment_1(), "rule__BarChart__NameAssignment_1");
					put(grammarAccess.getBarChartAccess().getTitleAssignment_2_1(), "rule__BarChart__TitleAssignment_2_1");
					put(grammarAccess.getBarChartAccess().getLegendPositionAssignment_3_1(), "rule__BarChart__LegendPositionAssignment_3_1");
					put(grammarAccess.getBarChartAccess().getLabelStringXAxesAssignment_4_1(), "rule__BarChart__LabelStringXAxesAssignment_4_1");
					put(grammarAccess.getBarChartAccess().getColorGridLinesXAxesAssignment_5_1(), "rule__BarChart__ColorGridLinesXAxesAssignment_5_1");
					put(grammarAccess.getBarChartAccess().getLabelStringYAxesAssignment_6_1(), "rule__BarChart__LabelStringYAxesAssignment_6_1");
					put(grammarAccess.getBarChartAccess().getColorGridLinesYAxesAssignment_7_1(), "rule__BarChart__ColorGridLinesYAxesAssignment_7_1");
					put(grammarAccess.getBarChartAccess().getBarPercentageAssignment_8_1(), "rule__BarChart__BarPercentageAssignment_8_1");
					put(grammarAccess.getBarChartAccess().getDisplayGridLinesXAxesAssignment_9(), "rule__BarChart__DisplayGridLinesXAxesAssignment_9");
					put(grammarAccess.getBarChartAccess().getDisplayGridLinesYAxesAssignment_10(), "rule__BarChart__DisplayGridLinesYAxesAssignment_10");
					put(grammarAccess.getBarChartAccess().getDataAssignment_14(), "rule__BarChart__DataAssignment_14");
					put(grammarAccess.getBarChartAccess().getDataAssignment_15_1(), "rule__BarChart__DataAssignment_15_1");
					put(grammarAccess.getBarChartAccess().getLabelsAssignment_20(), "rule__BarChart__LabelsAssignment_20");
					put(grammarAccess.getBarChartAccess().getLabelsAssignment_21_1(), "rule__BarChart__LabelsAssignment_21_1");
					put(grammarAccess.getRadarChartAccess().getNameAssignment_1(), "rule__RadarChart__NameAssignment_1");
					put(grammarAccess.getRadarChartAccess().getTitleAssignment_2_1(), "rule__RadarChart__TitleAssignment_2_1");
					put(grammarAccess.getRadarChartAccess().getLegendPositionAssignment_3_1(), "rule__RadarChart__LegendPositionAssignment_3_1");
					put(grammarAccess.getRadarChartAccess().getAngleLinesDisplayAssignment_4(), "rule__RadarChart__AngleLinesDisplayAssignment_4");
					put(grammarAccess.getRadarChartAccess().getDataAssignment_8(), "rule__RadarChart__DataAssignment_8");
					put(grammarAccess.getRadarChartAccess().getDataAssignment_9_1(), "rule__RadarChart__DataAssignment_9_1");
					put(grammarAccess.getRadarChartAccess().getLabelsAssignment_14(), "rule__RadarChart__LabelsAssignment_14");
					put(grammarAccess.getRadarChartAccess().getLabelsAssignment_15_1(), "rule__RadarChart__LabelsAssignment_15_1");
					put(grammarAccess.getPieChartAccess().getNameAssignment_2(), "rule__PieChart__NameAssignment_2");
					put(grammarAccess.getPieChartAccess().getTitleAssignment_3_1(), "rule__PieChart__TitleAssignment_3_1");
					put(grammarAccess.getPieChartAccess().getLegendPositionAssignment_4_1(), "rule__PieChart__LegendPositionAssignment_4_1");
					put(grammarAccess.getPieChartAccess().getDataAssignment_8(), "rule__PieChart__DataAssignment_8");
					put(grammarAccess.getPieChartAccess().getDataAssignment_9_1(), "rule__PieChart__DataAssignment_9_1");
					put(grammarAccess.getPieChartAccess().getLabelsAssignment_14(), "rule__PieChart__LabelsAssignment_14");
					put(grammarAccess.getPieChartAccess().getLabelsAssignment_15_1(), "rule__PieChart__LabelsAssignment_15_1");
					put(grammarAccess.getActionAccess().getNameAssignment_2(), "rule__Action__NameAssignment_2");
					put(grammarAccess.getActionAccess().getColumnTitleAssignment_3_1(), "rule__Action__ColumnTitleAssignment_3_1");
					put(grammarAccess.getActionAccess().getPositionAssignment_4_1(), "rule__Action__PositionAssignment_4_1");
					put(grammarAccess.getActionAccess().getAddAssignment_5(), "rule__Action__AddAssignment_5");
					put(grammarAccess.getActionAccess().getFilterAssignment_6(), "rule__Action__FilterAssignment_6");
					put(grammarAccess.getActionAccess().getEditAssignment_7(), "rule__Action__EditAssignment_7");
					put(grammarAccess.getActionAccess().getDeleteAssignment_8(), "rule__Action__DeleteAssignment_8");
					put(grammarAccess.getColumnAccess().getNameAssignment_2(), "rule__Column__NameAssignment_2");
					put(grammarAccess.getColumnAccess().getTitleAssignment_3_1(), "rule__Column__TitleAssignment_3_1");
					put(grammarAccess.getColumnAccess().getSourceAssignment_4_1(), "rule__Column__SourceAssignment_4_1");
					put(grammarAccess.getColumnAccess().getFilterAssignment_5(), "rule__Column__FilterAssignment_5");
					put(grammarAccess.getColumnAccess().getEditableAssignment_6(), "rule__Column__EditableAssignment_6");
					put(grammarAccess.getDataAccess().getNameAssignment_1(), "rule__Data__NameAssignment_1");
					put(grammarAccess.getDataAccess().getCategoryAssignment_2_1(), "rule__Data__CategoryAssignment_2_1");
					put(grammarAccess.getDataAccess().getBorderColorAssignment_3_1(), "rule__Data__BorderColorAssignment_3_1");
					put(grammarAccess.getDataAccess().getBackgroundColorAssignment_4_1(), "rule__Data__BackgroundColorAssignment_4_1");
					put(grammarAccess.getDataAccess().getBorderDashAssignment_5_1(), "rule__Data__BorderDashAssignment_5_1");
					put(grammarAccess.getDataAccess().getFillAssignment_6(), "rule__Data__FillAssignment_6");
					put(grammarAccess.getDataAccess().getDataAssignment_9(), "rule__Data__DataAssignment_9");
					put(grammarAccess.getDataAccess().getDataAssignment_10_1(), "rule__Data__DataAssignment_10_1");
					put(grammarAccess.getLabelAccess().getNameAssignment_2(), "rule__Label__NameAssignment_2");
					put(grammarAccess.getDBServerAccess().getNameAssignment_1(), "rule__DBServer__NameAssignment_1");
					put(grammarAccess.getDBServerAccess().getSystemManagerAssignment_2_1(), "rule__DBServer__SystemManagerAssignment_2_1");
					put(grammarAccess.getDBServerAccess().getTokenAssignment_3_1(), "rule__DBServer__TokenAssignment_3_1");
					put(grammarAccess.getDBServerAccess().getPasswordAssignment_4_1(), "rule__DBServer__PasswordAssignment_4_1");
					put(grammarAccess.getDBServerAccess().getRelatedCollectionsAssignment_8(), "rule__DBServer__RelatedCollectionsAssignment_8");
					put(grammarAccess.getDBServerAccess().getRelatedCollectionsAssignment_9_1(), "rule__DBServer__RelatedCollectionsAssignment_9_1");
					put(grammarAccess.getCollectionAccess().getNameAssignment_1(), "rule__Collection__NameAssignment_1");
					put(grammarAccess.getCollectionAccess().getDocumentsAssignment_5(), "rule__Collection__DocumentsAssignment_5");
					put(grammarAccess.getCollectionAccess().getDocumentsAssignment_6_1(), "rule__Collection__DocumentsAssignment_6_1");
					put(grammarAccess.getDocumentAccess().getNameAssignment_2(), "rule__Document__NameAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public MyDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MyDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
